apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: primaryEncryptionKey
    secretKeyRef:
      name: mykey        # <-- TÊN của secret bên trong file JSON
  # optional: secondaryEncryptionKey tương tự
auth:
  secretStore: localsecretstore   # <-- TÊN của secret store
